name: Pipeline 4 - Gerar Relatorios

on:
  workflow_dispatch: # Habilita a execucao manual na aba "Actions"

jobs:
  gerar-e-salvar:
    runs-on: ubuntu-latest

    steps:
      - name: Realizar Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependencias
        run: npm install

      - name: Executar script de relatorio
        run: npm run stats

      - name: Upload da pasta de Relatorios (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-gerados # Nome do arquivo que sera baixado no GitHub
          path: reports/ # Caminho da pasta que sera zipada e salva
