name: Pipeline 1 - Integracao Continua

on:
  push:
    branches: ["main", "develop"]
  pull_request:
    branches: ["main", "develop"]

jobs:
  build-e-validacao:
    runs-on: ubuntu-latest

    steps:
      - name: Realizar Checkout do codigo
        uses: actions/checkout@v4

      - name: Configurar Node.js e Cache NPM
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # Atende ao requisito de "cache npm"

      - name: Instalar dependencias
        run: npm install

      - name: Executar Eslint (Lint)
        run: npm run lint

      - name: Executar Prettier (Formatacao)
        run: npm run format

      - name: Executar Build
        run: |
          mkdir -p dist
          npm run build
